### ISSUE TITLE
Ability to "wake up" display from users home automation system

### ISSUE THREAD

**Issue by cablesandcoffee** [tpanajott/NSPanelManager#17]
User should be able to wake the display up from HA/OH.

For example if a user has movement sensors they might want the display for that room to wake when someone enters the room.
I guess this should be done by having a "Wake Up" topic for each display that user can send a command to from HA/OH.

**Comment by tpanajott** [comment]
That would be the simplest solution, yes. Simply a topic that if you send "1" it will turn on and "0" it will turn off. This would also make it simple to implement as a "switch" in a users home automation software and the panel could back feed information and update the topic based in state as well. If the panel goes to sleep, send a "0", if it wakes up, send a "1".

**Comment by tpanajott** [comment]
Use the topics nspanel/<panel name>/screen_state or /screen_cmd to recieve/send "1" or "0"

**Comment by cablesandcoffee** [comment]
Cool! Works like a charm!
