### ISSUE TITLE
Room page needs "touch caps"

### ISSUE THREAD

**Issue by tpanajott** [tpanajott/NSPanelManager#20]
The "Room" page needs the same treatment as the home page, by blocking the user from touching the switch directly.

**Comment by cablesandcoffee** [comment]
Just so I understand correctly. One touch cap/switch = 12 touch caps on room page.

**Comment by tpanajott** [comment]
Yes, note that I have made some changes to the TFT file so you need to pull the latest data first.

**Comment by tpanajott** [comment]
Fixed with commit 11b8b9600c23e4c3a4c21d682b7bf89163dcef08
