### ISSUE TITLE
Light placement on Room page does not work for row 11 and 12

### ISSUE THREAD

**Issue by cablesandcoffee** [tpanajott/NSPanelManager#25]
If placing a light on row 11 i shows on both row 11 and 12.
If placing a light on row 12 it does not show anywhere.

![Screenshot from 2023-04-10 12-45-12](https://user-images.githubusercontent.com/63468500/230887281-d0bb2213-aa4b-40bf-a85f-9aea4b903794.png)

**Comment by tpanajott** [comment]
Fixed, copy-paste error
