### ISSUE TITLE
Room lights mode + changing kelvin slider

### ISSUE THREAD

**Issue by cablesandcoffee** [tpanajott/NSPanelManager#4]
Expected Behavior
If no lights on. Nothing should happen
If 1 or more lights are on only the ones that are on should change

Actual Behavior
When no lights on, both ceiling and table lights turn on
If only ceiling on, table lights turn on as well and vice versa.

**Comment by tpanajott** [comment]
Work has begun in order to fix this in the MQTTManager, this should already be fixed but it needs verification for OpenHAB. It's working for Home Assistant with the newest release.

**Comment by cablesandcoffee** [comment]
Works in Openhab as well! Great work! :)
