### ISSUE TITLE
All lights mode, table lights on in one room + changing brightness dimmer

### ISSUE THREAD

**Issue by cablesandcoffee** [tpanajott/NSPanelManager#5]
Expected Behavior
Only the lights that are currently on in house should change. Ceiling or table lights symbols that are off in other rooms should not become yellow.

Actual Behavior
Only the lights that are on changes in real life.
But when switching to another room the table lights symbol has become yellow there as well all though those lights are not on.

**Comment by tpanajott** [comment]
Is this the same as issue #3

**Comment by cablesandcoffee** [comment]
Not sure but it is definitely solved!
