### ISSUE TITLE
Update Add lights window to support Switches

### ISSUE THREAD

**Issue by cablesandcoffee** [tpanajott/NSPanelManager#6]
**Current behaviour**
Currently an Openhab user is able to add a light that is of type Switch in the Add lights window but Openhab throws an error when NSPM is sending a percent value to the switch and the light is neither turned on or off.

Error from Openhab log: 
`[hab.core.io.websocket.EventWebSocket] - Failed to process deserialized event '{"type": "ItemCommandEvent", "topic": "openhab/items/Outlet2LightsMirror_Brightness/command", "payload": "{\"type\":\"Percent\",\"value\":\"0\"}", "source": "WebSocketNSPanelManager"}': Incompatible datatype, rejected.`

**Expected Behaviour**
If brightness slider > 0 a light of type Switch should turn on
If brightness slider = 0 light of type Switch should turn off

Solution:
Add "Switch" as capability in Add lights window to know when to use the payload shown below.

For switches the payload sent on Openhab websocket must look like this:
"payload": "{\"type\":\"OnOff\",\"value\":\"ON\"}"

**Comment by tpanajott** [comment]
This should work as of commit 7728d939cb8d5ea881a9acd4778a080784f17fe4 but it requires further testing/verification

**Comment by cablesandcoffee** [comment]
I can see that the add light window has been updated but it does not seem to work perfectly just yet. It looks like this:

![Screenshot from 2023-03-26 18-37-25](https://user-images.githubusercontent.com/63468500/227790453-5ce76f04-af6a-4a1a-a321-a04ea45036db.png)


The switch item is presented in Dimming , Color and RGB drop downs but not in Switch drop down. Get error when trying to add light as well:

![Screenshot from 2023-03-26 18-39-05](https://user-images.githubusercontent.com/63468500/227790560-e89b5f43-6d4f-4534-b0bf-b08fabe1a42c.png)

**Comment by tpanajott** [comment]
Try clearing the browser cache by holding shift while pressing the "reload"-button.

**Comment by tpanajott** [comment]
Tested this issue using the latest code and can add lights as switches without it crashing. This requires more information. Can you please provide the whole page for the error?

**Comment by cablesandcoffee** [comment]
Works after clearing cache. No issues with adding lights so everything seems solved.
