### ISSUE TITLE
Update New Lights window to show Item choices based on Capabilities

### ISSUE THREAD

**Issue by cablesandcoffee** [tpanajott/NSPanelManager#8]
Not sure if this affects the Home Assistant users so tagged as Openhab related.

**Current behavior:**
When adding a light all possible Item choices are shown all though maybe only Dimming capability has been chosen. 

**Future behavior:**
Show Item choices based on which capabilities the user has chosen for the specific light.

**Solution suggestion:**
1. User adds new light
2. Chooses Thing

3. Add new light to room-window appears
4. No capabilities are pre-chosen. No Item drop downs are available either.
5. User ticks in capabilities for light
6. For each capability chosen Item drop downs appear.

I guess it should not be possible to choose Dimmable and Switch capability on the same light?
The only purpose of being able to chose Switch is to be able to control a light that is controlled via an outlet.
I'm saying this because a user in Openhab can have a switch and dimmer Item connected to the same channel and might make that choice but we are in no use of knowing that. It just complicates things. If light is dimmable capable that is the choice the user needs to make.

If Switch is chosen: All other capabilites are grayed out?
If Dimmable is chosen: Switch is Grayed out?

**Comment by tpanajott** [comment]
Fixed as of commit 6d994b6639ecb7fe5211fda36e295ed9834027a6
