### ISSUE TITLE
All lights mode not settings lights to the same brightness

### ISSUE THREAD

**Issue by cablesandcoffee** [tpanajott/NSPanelManager#9]
**Conditions:**
Panel in All Lights mode. Lights are on in several rooms and they are set to different percentages.

**Current behavior:**
When using the brightness slider all Lights that are on does not get the value where the user released the slider. Different values are passed to the lights and very soon after release the slider jumps to a new value.

**Expected behavior:**
All lights that are on should get the exact same value. The value where the slider was released.

**Comment by tpanajott** [comment]
This might be because of trying to send to many MQTT messages, rework has begun to only send one MQTT-messages from the panel in order to reduce this risk of this

**Comment by cablesandcoffee** [comment]
Can't see any issues any more. Closing!
